# .streamlit/secrets.toml

attend_url = "https://docs.google.com/spreadsheets/d/1AG89W1nwRzZxYreM6i1qmwS6APf-8GM2K_HDyX7REG4/edit#gid=0"
course_url = "https://docs.google.com/spreadsheets/d/1AG89W1nwRzZxYreM6i1qmwS6APf-8GM2K_HDyX7REG4/edit#gid=591706408"
month_url = "https://docs.google.com/spreadsheets/d/1AG89W1nwRzZxYreM6i1qmwS6APf-8GM2K_HDyX7REG4/edit#gid=216302834"
regist_url = "https://docs.google.com/spreadsheets/d/1AG89W1nwRzZxYreM6i1qmwS6APf-8GM2K_HDyX7REG4/edit#gid=1608447947"
log_url = "https://docs.google.com/spreadsheets/d/1AG89W1nwRzZxYreM6i1qmwS6APf-8GM2K_HDyX7REG4/edit#gid=818416531"
jan_url = "https://docs.google.com/spreadsheets/d/1ScB72IK-vu8KmU5heClv4m7a1ZMG8t1juc5DEVTuIQE/edit#gid=0"
feb_url = "https://docs.google.com/spreadsheets/d/1vq3dXH73OG-umx2YADmOyV2B8kfHaamy1bi3tTQvfJU/edit#gid=0"
mar_url = "https://docs.google.com/spreadsheets/d/14TdSj4ku9CU5i0j77Ejvg7KvdF36M-7rImLkGAE2iHM/edit#gid=0"
apr_url = "https://docs.google.com/spreadsheets/d/1KatROnJt86sNwzgkgnL34_x-KQwgNJRYzWZNOvJb6A8/edit#gid=0"
may_url = "https://docs.google.com/spreadsheets/d/1S0T8Ntbphum1T2e2aGRyjSbZrLdagiOwPF1LFyxte4I/edit#gid=0"
jun_url = "https://docs.google.com/spreadsheets/d/185FxfFDF1ZFkGaXxkGhC3DG9U-j7FGVCX3X4y7J4Y3A/edit#gid=0"
jul_url = "https://docs.google.com/spreadsheets/d/1KCfmtU6adC19QHALmf9SVu_3Kx9LnM1ohTHfvAI9RiQ/edit#gid=0"
aug_url = "https://docs.google.com/spreadsheets/d/18Hn98gulQ2Z1CGgDuJtZE6Lanl30lkSixb7LiIUZPmw/edit#gid=0"
sep_url = "https://docs.google.com/spreadsheets/d/1PzrsAgaANO4G4lvpPh-DIXgi0Wepj9POgEK09Yv7G1Q/edit#gid=0"
oct_url = "https://docs.google.com/spreadsheets/d/1huGFTdQ_qVy5-vTLy7AWm1vpuf9I-U7SOqG1c-G6QXk/edit#gid=0"
nov_url = ""
dec_url = ""
fa_url = "https://docs.google.com/spreadsheets/d/1d9zbGo7SmAhGtPedX-yhui4WNKJ7blvbBzvXYwzzv9U/edit#gid=0"
enter_url = "https://docs.google.com/spreadsheets/d/1d9zbGo7SmAhGtPedX-yhui4WNKJ7blvbBzvXYwzzv9U/edit#gid=1268749737"
quit_url = "https://docs.google.com/spreadsheets/d/1d9zbGo7SmAhGtPedX-yhui4WNKJ7blvbBzvXYwzzv9U/edit#gid=381987342"
branch_url = "https://docs.google.com/spreadsheets/d/1d9zbGo7SmAhGtPedX-yhui4WNKJ7blvbBzvXYwzzv9U/edit#gid=826612733"
open_url = "https://docs.google.com/spreadsheets/d/1d9zbGo7SmAhGtPedX-yhui4WNKJ7blvbBzvXYwzzv9U/edit#gid=1183292674"
close_url = "https://docs.google.com/spreadsheets/d/1d9zbGo7SmAhGtPedX-yhui4WNKJ7blvbBzvXYwzzv9U/edit#gid=378770349"