# .streamlit/secrets.toml

attend_url = "https://docs.google.com/spreadsheets/d/1YLN2Rs-WjGTdhZHW-9TMAUIMCC_8lQ3XZpoPlnShesQ/edit#gid=0"
course_url = "https://docs.google.com/spreadsheets/d/1nFfsAClGgpeT5yR70WTY-3I8Htxtex37jU-DPyp2PUY/edit#gid=0"
apply_url = "https://docs.google.com/spreadsheets/d/1ZciFiHjJnO6mteB3k2dbT4MD-OhAX4rG4JCVQHFFkBg/edit#gid=0"
regist_url = "https://docs.google.com/spreadsheets/d/1AG89W1nwRzZxYreM6i1qmwS6APf-8GM2K_HDyX7REG4/edit#gid=1608447947"